[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
poem.workspace = true
config.workspace = true
serde.workspace = true
clap.workspace = true
anyhow.workspace = true
snafu.workspace = true
ftlog.workspace = true
time.workspace = true
