services:
    # Grafana 服务配置
    grafana:
        image: grafana/grafana:12.0.0
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_SERVER_DOMAIN=destinyfvcker.cn
            - GF_SERVER_ROOT_URL=https://destinyfvcker.cn/grafana
            # - GF_SERVER_SERVE_FROM_SUB_PATH=true
        restart: unless-stopped
        networks:
            - monitoring

    # AKShare 服务配置
    aktools:
        build:
            dockerfile: ./docker/aktools.dockerfile
        ports:
            - "8080:8080"
        networks:
            - monitoring

    # MySQL 服务配置
    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped
        networks:
            - monitoring

    clickhouse:
        image: clickhouse/clickhouse-server:25.3.1
        container_name: clickhouse
        ports:
            - "8123:8123" # HTTP接口
            - "9000:9000" # 客户端接口
            - "9009:9009" # 复制端口
        environment:
            - CLICKHOUSE_USER=${CLICKHOUSE_USER}
            - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
            - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 # 启用访问控制
            - CLICKHOUSE_MAX_SERVER_MEMORY_USAGE_RATIO=0.7 # 限制内存使用率为70%
            - CLICKHOUSE_MAX_MEMORY_USAGE=2800000000 # 约2.8GB最大内存使用
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - type: bind
              read_only: true
              source: ./docker/config-logs.xml
              target: /etc/clickhouse-server/config.d/config-logs.xml
        # ulimits:
        #     nofile:
        #         soft: 32768
        #         hard: 65536
        restart: unless-stopped
        networks:
            - monitoring

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        restart: unless-stopped
        networks:
            - monitoring

        # ZooKeeper服务配置
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181 # ZooKeeper客户端连接端口
            ZOOKEEPER_TICK_TIME: 2000 # ZooKeeper心跳间隔时间（毫秒）
        ports:
            - "2181:2181"
        volumes:
            - zookeeper-data:/var/lib/zookeeper/data
            - zookeeper-log:/var/lib/zookeeper/log
        networks:
            - monitoring

    # Kafka服务配置
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092" # 对外暴露的Kafka端口
            - "29092:29092" # 内部容器通信端口
        environment:
            KAFKA_BROKER_ID: 1 # Kafka broker的唯一标识
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # 连接到ZooKeeper的地址
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 # 广告监听器配置
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT # 安全协议映射
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT # Broker间通信使用的监听器名称
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # 偏移量主题的复制因子
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # 允许自动创建主题
        volumes:
            - kafka-data:/var/lib/kafka/data
        networks:
            - monitoring

    # Kafka管理界面（可选组件）
    kafka-ui:
        image: provectuslabs/kafka-ui:v0.7.2
        container_name: kafka-ui
        depends_on:
            - kafka
        ports:
            - "8081:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: local # 集群名称
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092 # Kafka服务器地址
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 # ZooKeeper地址
            SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
            AUTH_TYPE: "LOGIN_FORM"
            SPRING_SECURITY_USER_NAME: ${KAFKA_UI_USER}
            SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASSWORD}
        networks:
            - monitoring

volumes:
    grafana_data:
    mysql_data:
    clickhouse_data:
    redis_data:
    zookeeper-data:
    zookeeper-log:
    kafka-data:

networks:
    monitoring:
        driver: bridge
