[server]
port = 18803
# logdir = ? (in env)

[clickhouse]
host = "127.0.0.1"
port = 8123
database = "akshare"
# user = ? (in env)
# password = ? (in env)

[kafka]
broker = "localhost:9092"
topic = "grafana_alarm"
partition = 0
