[server]
fe = "/home/destinyfvcker/projects/data-mind/fe"
port = 8800
deploy_path = "https://www.destinyfvcker.com/data-mind"
# deploy_path = "http://localhost:5173/data-mind"
# fe = "/Users/zilu/dev/fe-dev/projects/datamind-fe/build"

[coze]
# id = ? (in env)
# kid = ? (in env)
# signingkey = ? (in env)

[clickhouse]
host = "127.0.0.1"
port = 8123
# user = ? (in env)
# password = ? (in env)
database = "akshare"

[mysql]
host = "127.0.0.1"
port = 3306
# user = ? (in env)
# password = ? (in env)
database = "data_mind"

[github]
client_id = "Ov23lim6oTncg9iWxk1T"
# secret = ? (in env)

[kafka]
broker = "localhost:9092"
topic = "grafana_alarm"
partition = 0
