name: web server
on:
    workflow_dispatch:
    pull_request:
        types:
            - closed
        paths:
            - _web-server/**
env:
    CARGO_TERM_COLOR: always
    APP_NAME: web_server
    BASE_PATH: "/home/${{ secrets.ALIYUN_USER }}/projects/data-mind/"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install Protoc
              uses: arduino/setup-protoc@v3
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - uses: dtolnay/rust-toolchain@nightly
            - name: Build
              run: cargo build -p $APP_NAME -r
            # 创建部署目录结构
            - name: Create deployment directory structure
              run: |
                  mkdir -p deploy/conf
                  cp target/release/${APP_NAME} deploy/
                  cp scripts/restart_${APP_NAME}.sh deploy/
                  cp conf/${APP_NAME}.toml deploy/conf/ || echo "No configuration files found"
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.APP_NAME }}
                  path: deploy/
                  compression-level: 9
                  retention-days: 5
    deploy:
        name: Deploy to Aliyun Server
        needs: build
        runs-on: ubuntu-latest
        environment: Aliyun production
        steps:
            # 下载构建产物
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: ${{ env.APP_NAME }}
                  path: ./deploy
            # 部署到阿里云服务器
            - name: Deploy to Aliyun
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.ALIYUN_HOST }}
                  REMOTE_USER: ${{ secrets.ALIYUN_USER }}
                  ARGS: "-avzr --delete --mkpath --exclude='PID'"
                  SOURCE: "./deploy/"
                  TARGET: ${{ env.BASE_PATH }}${{ env.APP_NAME }}/
            # 重启服务
            - name: Restart service using SSH Remote Commands
              uses: appleboy/ssh-action@v1.2.1
              env:
                  CLICKHOUSE_USER: ${{ secrets.WEB_SERVER_CH_USER }}
                  CLICKHOUSE_PASSWORD: ${{ secrets.AK_SHARE_READER_PASSWORD }}
                  MYSQL_USER: root
                  MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
                  GITHUB_SECRET: ${{ secrets.MY_GITHUB_SECRET }}
              with:
                  host: ${{ secrets.ALIYUN_HOST }}
                  username: ${{ secrets.ALIYUN_USER }}
                  key: ${{ secrets.ALIYUN_SSH_KEY }}
                  envs: BASE_PATH,APP_NAME,CLICKHOUSE_USER,CLICKHOUSE_PASSWORD
                  # 设置环境变量并执行脚本
                  script: |
                      cd ${BASE_PATH}${APP_NAME}
                      chmod +x ./$APP_NAME
                      chmod +x ./restart_${APP_NAME}.sh
                      ./restart_${APP_NAME}.sh
