name: Build and deploy to aliyun(web server)
on:
    push:
        branches: ["main"]
env:
    CARGO_TERM_COLOR: always
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: cargo build -p web_server --release
            # 创建部署目录结构
            - name: Create deployment directory structure
              run: |
                  mkdir -p deployment/conf
                  cp target/release/web_server deployment/
                  cp scripts/restart_web_server.sh deployment/
                  chmod +x deployment/restart_web_server.sh
                  cp -r conf/* deployment/conf/ || echo "No configuration files found"
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: web-server-release
                  path: deployment/
                  compression-level: 9
                  retention-days: 5
    deploy:
        name: Deploy to Aliyun Server
        needs: build
        runs-on: ubuntu-latest
        env:
            DEPLOY_PATH: "/opt/rust-server/"
        steps:
            # 下载构建产物
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: web-server-release
                  path: ./deploy-package
            # 部署到阿里云服务器
            - name: Deploy to Aliyun
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.ALIYUN_HOST }}
                  REMOTE_USER: ${{ secrets.ALIYUN_USER }}
                  ARGS: "-avzr --delete --mkpath"
                  SOURCE: "./deploy-package/"
                  TARGET: "/home/${{ secrets.ALIYUN_USER }}/projects/data-mind/web-server/"
            # 重启服务
            # - name: Restart service
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: ${{ secrets.ALIYUN_HOST }}
            #       username: ${{ secrets.ALIYUN_USER }}
            #       key: ${{ secrets.ALIYUN_SSH_KEY }}
            #       script: |
            #           cd /opt/rust-server/
            #           export SHOME="/opt/rust-server"
            #           ./restart_web_server.sh
            #           echo "服务已使用restart_web_server.sh成功重启！"
